### ISSUE TITLE
Create new unique parameter names from stratification

### ISSUE THREAD

**Issue by SamWitty** [indralab/mira#157]
Currently, stratification appears to create new state variables and new transitions between state variables, but does not create new unique parameter names for those transitions. We (CIEMSS) use these parameter names to instantiate Pyro parameters, so we need any parameter values that are not shared across multiple transitions to have unique names.

For example, in (https://github.com/DARPA-ASKEM/program-milestones/blob/main/6-month-milestone/evaluation/scenario_1/ta_2/scenario1_three_ages.json), transition "t1" and "t2" both use that parameter name "mira_param_strat_0", but the parameter values could differ. 

My concrete suggestion would be to either (1) have a separate field for unique parameters, each of which contains a name, an id, and a value, and then have transitions refer to parameters by id only, or (2) always construct new parameter names after stratification.

(1) above seems more general, as it would straightforwardly allow parameters to be shared when needed. Happy to discuss more.

**Comment by bgyori** [comment]
In the latest implementation of stratification you can control in a granular way how parameters should be split with all options available (no splitting, full splitting, specific parameter splitting).
