### ISSUE TITLE
MathML markup node questions

### ISSUE THREAD

**Issue by anandijain** [indralab/mira#159]
im looking at the mathml rate laws for the miranets 

```
"mira_rate_law_mathml": "...ci><mml:msub><mml:mi>ModelValue</mml:mi><mml:mi>5</mml:mi></mml:msub></ci><cn>2</cn></apply><ci>Susceptible</ci><ci><mml:msub><mml:mi>&#946;</mml:mi><mml:mrow><mml:mi>1</mml:mi><mml:mo> </mml:mo><mml:mi>USA</mml:mi></mml:mrow></mml:msub></ci><ci><mml:msub><mml:mi>l</mml:mi><mml:mrow><mml:mi>1</mml:mi><mml:mo> </mml:mo><mml:mi>USA</mml:mi></mml:mrow></mml:msub></ci></apply><apply><plus/><apply><times/><ci><mml:msub><mml:mi>ModelValue</mml:mi><mml:mi>135</mml:mi></mml:msub></ci><ci><mml:msub><mml:mi>ModelValue</mml:mi><mml:mi>5</mml:mi></mml:msub></ci></apply><cn>11000000.0</cn></apply></apply>",
```

and it's a bit frustrating tha twe have these subscripts and and the mml xml namespaced nodes. is it possible we could change this to just be the expression tree?

my understanding is that the mathml markup nodes (all the mml) are only used for rendering and formatting. i think if we want to just represent the expression, we should remove them. (also partly because the MML parser i wrote in julia doesn't handle any of the markup nodes)

**Comment by bgyori** [comment]
I see, this is due to the fact that some parameters in these models have underscores in their name, and this formatting is done by sympy's mathml exporter like this.

```python
In [21]: exp1 = sympy.Symbol('a') * sympy.Symbol('b')

In [22]: exp2 = sympy.Symbol('a_1') * sympy.Symbol('b')

In [23]: mathml(exp1)
Out[23]: '<apply><times/><ci>a</ci><ci>b</ci></apply>'

In [24]: mathml(exp2)
Out[24]: '<apply><times/><ci><mml:msub><mml:mi>a</mml:mi><mml:mi>1</mml:mi></mml:msub></ci><ci>b</ci></apply>'
```

I will look into avoiding the additional styling sympy's exporter does for underscores without actually having to modify the original parameter names.

**Comment by anandijain** [comment]
I can look into SymPy.jl or pycall to parse them too

**Comment by bgyori** [comment]
I'm testing a solution for this now, should be done shortly.

**Comment by bgyori** [comment]
It turns out, dealing with underscores is not enough. A second case in which subscripts are introduced is when symbols end in numbers, even without an underscore before the number. For example:
```python
In [2]: exp1 = sympy.Symbol('a1')
In [4]: mathml(exp1)
Out[4]: '<ci><mml:msub><mml:mi>a</mml:mi><mml:mi>1</mml:mi></mml:msub></ci>'
```
I'll continue to look for a way to avoid this.

**Comment by bgyori** [comment]
@anandijain take a look at https://github.com/indralab/mira/blob/ensemble/notebooks/ensemble/BIOMD0000000960_miranet.json. Let me know if you notice any other MathML issue.

**Comment by anandijain** [comment]
im able to parse it now! thanks a ton
