### ISSUE TITLE
Need a round-trip path for AskeNet <-> Mira

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#169]
Hi folks,

AskeNet models make it easy to generate the AskeNet serialization from a Mira model, but not easy to generate a Mira model from an AskeNet model.  PR https://github.com/indralab/mira/pull/168 and PR https://github.com/indralab/mira/pull/167 complete the round trip for Regnets and Petrinets, respectively

**Comment by bgyori** [comment]
Given the additional functions in #170 can this issue and the two PRs be closed? Or should I add anything else?

**Comment by djinnome** [comment]
No, this is all good.  Let me know when you have merged #170 into main.

**Comment by bgyori** [comment]
I actually merged #170 yesterday so all those are now available on the main branch.
