### ISSUE TITLE
Should aggregate_parameters include total population in the denominator?

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#172]
Hi folks,

I have posted this issue because I think this is potentially a case of semantics creeping into the syntax.

In second-order mass balance equations, the semantics of infection are as follows:

$$S + I \xrightarrow{\beta} I + I$$
implies

$$\frac{dI}{dt} = \beta\frac{[S]\cdot[I]}{[S] + [I] + [R]}$$

where $[S] + [I] + [R]$ is the total population.
However, when running `aggregate_parameters`, it combines both the total population and the rate parameter into one aggregated parameter:  $\theta_{mira} = \frac{\beta}{[S]+[I]+[R]}$
Thus when applying the semantics of second-order mass balance, we end up dividing by the total population twice.

$$\frac{dI}{dt} = \theta_{mira}\frac{[S]\cdot[I]}{[S] + [I] + [R]}$$

Should we change the semantics of `aggregate_parameters` or change the semantics of second order equations?

**Comment by djinnome** [comment]
For more information see https://github.com/ciemss/pyciemss/issues/160

**Comment by djinnome** [comment]
I now notice that the rate law in my biomodel template is different from the rate law in the current biomodel  template:

From: https://github.com/indralab/mira/blob/2ffd949814f8a97ad776dc46fe73c0239e58248d/notebooks/ensemble/BIOMD0000000960_template_model.json#L1-L11

From:
https://github.com/ciemss/pyciemss/blob/b15d214c188d84d02bc64793679c88fea2030da1/test/models/april_ensemble_demo/BIOMD0000000960_template_model.json#L1-L10

```json
{
 "templates": [
  {
   "rate_law":  "Infectious*ModelValue_5*Susceptible*beta_1_USA/(ModelValue_135*ModelValue_5 + 11000000.0)",

   "type": "ControlledConversion",
   "controller": {
    "name": "Infectious",
    "identifiers": {
     "ido": "0000511"
    },
```

**Comment by djinnome** [comment]
Yes, the issue I described still applies here.  `aggregate_parameters` unwittingly aggregates the total population into the parameter, thus we "double divide" by the total population in the ODE.

**Comment by bgyori** [comment]
I'm still not sure I understand the issue. Assume we have a rate law of the form

$$\frac{dI}{dt} = \beta\frac{[S]\cdot[I]}{N}$$

and $N$ is considered a static parameter, MIRA's `aggregate_parameters` make this

$$\frac{dI}{dt} = p[S]\cdot[I]$$ 

with $p := \frac{\beta}{N}$.

I checked specifically [the model you linked to](https://github.com/indralab/mira/blob/2ffd949814f8a97ad776dc46fe73c0239e58248d/notebooks/ensemble/BIOMD0000000960_template_model.json#L1-L11), and `aggregate_parameters` turns

```
Infectious*Susceptible*beta_1_USA/Total_pop_USA
```
with

```
beta_1_USA  = 0.303
Total_pop_USA  = 328200000.0
```

into
```
Infectious*Susceptible*mira_param_0
```
with
```
mira_param_0 =  9.23e-10
```

which seems to be the correct replacement.

**Comment by djinnome** [comment]
Hi @bgyori , 

We both agree that `aggregate_parameters` includes `Total_pop_USA` as a parameter.  The question is whether it should.  With some models, $\beta/N$ is the parameter associated with infection, and with other models (such as SIRD models), $N$ isn't a constant, so you need something like $\frac{\beta[S][I]}{[S] + [I] + [R]}$ (where $[D]$ is not part of the denominator).   
So from a consistency perspective, I would argue that it shouldn't be part of the parameter.

Also from a dimensional analysis perspective, the rate parameter should have units of $\frac{1}{day}$, but if we divide by population, then the rate parameter has units of  $\frac{1}{day\cdot person}$.  

Thus, to be consistent across units and models, I would argue that including the total population in an opaque aggregated parameter is problematic.  With that said, if units are provided, that might be enough of a hint to treat the parameter properly, but as it currently stands, the only reason we noticed was that the `mira_param_0` was **much** smaller than the other rate parameters.

Theq

**Comment by bgyori** [comment]
To clarify, MIRA will _not_ aggregate the total population if it is not a constant. In the model above, `Total_pop_USA` is a constant parameter and therefore gets aggregated. If a model uses something like `[S]+[I]+[R]` in the denominator, it will not be aggregated.

**Comment by bgyori** [comment]
@djinnome I have an idea: I could implement an argument to `aggregate_parameters` that allows you to exclude specific parameters from aggregation. It might behave like this:

Input:
$$dx/dt = alpha \cdot beta \cdot gamma \cdot x \cdot y$$

call
```python
aggregate_parameters(exclude={'beta'})
```

Output:
$$dx/dt = mira\textunderscore param\textunderscore 0 \cdot beta \cdot x \cdot y$$

This would allow you to select specific parameters that you choose to keep explicitly. What do you think?

**Comment by djinnome** [comment]
Neat idea! I like it!

**Comment by SamWitty** [comment]
@bgyori , now that we have custom rate laws (almost) implemented and merged in (see https://github.com/ciemss/pyciemss/pull/201) we're no longer planning on relying on the `aggregate_parameters` method. We're still using it for now for some light version of backwards compatibility, but I believe that shift makes this issue a lower priority from our perspective.
