### ISSUE TITLE
Mismatch between rate law symbols and state variable names

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#189]
Hi folks,

In the AMR format, rate laws are expressed as symbols using ASKENET State `id` not ASKENET State `name`, 

https://github.com/indralab/mira/blob/82421e4465edfb6eb27f811726d9745afb3d28e4/mira/sources/askenet/petrinet.py#L101

but MIRA only preserves the `name` field (unless the name is not present), and not the `id` when reading the AMR into a Mira model.

https://github.com/indralab/mira/blob/82421e4465edfb6eb27f811726d9745afb3d28e4/mira/sources/askenet/petrinet.py#L229

  This makes it difficult to automatically associate each sympy symbol with its corresponding state variable.
Is there a way to associate AMR ids with state variables in the MIRA model?  Maybe just add `id` as another key in the `variable.data` dictionary or perhaps as an `askenet:<id>` in the `identifiers` or `context` attribute?

**Comment by bgyori** [comment]
Yes, this can indeed happen if both an id and a name are specified and they are different. We will look into the best option to fix this.

**Comment by djinnome** [comment]
The main issue is that I need a reliable way to associate a symbol with a concept. One possibility is to include the symbol as an additional attribute of the Concept
