### ISSUE TITLE
Mira raises KeyError: 'value'  when parsing BIOMD0000000949

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#197]
I decided to go through all the Biomodels AMRs and see if I could load them, and got this mira error:

```python

../../mira/mira/sources/askenet/petrinet.py:106: in template_model_from_askenet_json
 
    param_values = {
>       p['id']: p['value'] for p in ode_semantics.get('parameters', [])
    }
E   KeyError: 'value'

../../mira/mira/sources/askenet/petrinet.py:107: KeyError
```

The problem appears to be that the AMR does not have  a value for the `baseline_dummy_variable` parameter:

https://github.com/DARPA-ASKEM/experiments/blob/953808422c72dd0ab91dc7114ff3e581dfef0dac/thin-thread-examples/mira_v2/biomodels/BIOMD0000000949/model_askenet.json#L339-L346

Even though the underlying SBML model does contain a value for the parameter

https://github.com/DARPA-ASKEM/experiments/blob/953808422c72dd0ab91dc7114ff3e581dfef0dac/thin-thread-examples/mira_v2/biomodels/BIOMD0000000949/src/main/Chitnis2008.xml#L853

**Comment by djinnome** [comment]
Other Biomodels that display the same phenotype are:

* BIOMD0000000956
* BIOMD0000000960
* BIOMD0000000982
* BIOMD0000000962
* BIOMD0000000969
* BIOMD0000000977
* BIOMD0000000983
* BIOMD0000000991
* BIOMD0000000963
* BIOMD0000000978

**Comment by bgyori** [comment]
See https://github.com/DARPA-ASKEM/experiments/tree/update_examples/thin-thread-examples/mira_v2/biomodels
