### ISSUE TITLE
Scenario 1c - Susceptible to infected rate law contains no state variables 

### ISSUE THREAD

**Issue by VigneshSella** [indralab/mira#198]
At https://github.com/indralab/mira/blob/1ba91be282d913d53d18da06625ec62f107d14de/notebooks/hackathon_2023.07/scenario1_c.json#L139C1-L139C6, 'S', 'I', 'N' are neglected. By comparison in scenario_1a.json, at https://github.com/ciemss/pyciemss/blob/6cbd328d7adff209eb603472e41af8f5b2c615fa/notebook/hackathon_prep/scenario1_a.json#L139, we have S*I/N .

**Comment by VigneshSella** [comment]
Same with scenario_1d and scenario_1d_normalized ^

**Comment by bgyori** [comment]
This is fixed in cd52ca4809e2be220a320ca00a4097a444e78bf6
