### ISSUE TITLE
scenario 1a contains a k parameter in the rate law that is not in the parameters section of the AMR

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#200]
The symbol `k` is referenced here:
Equation (9) on page 4 of:

> Tay, B. K., Roby, C. A., Wu, J. W., & Tan, D. Y. (2021). Dynamical analysis of universal masking on the pandemic. International Journal of Environmental Research and Public Health, 18(17). https://doi.org/10.3390/ijerph18179027

https://github.com/indralab/mira/blob/56bf4c0d77919142684c8cbfb3521b7bf4470888/notebooks/hackathon_2023.07/scenario1_a.json#L129

But is not in here:

https://github.com/indralab/mira/blob/56bf4c0d77919142684c8cbfb3521b7bf4470888/notebooks/hackathon_2023.07/scenario1_a.json#L175-L232

**Comment by bgyori** [comment]
@djinnome I think this is an issue with the version of the model you're looking at. I believe Sam pinned your model import temporarily to an old version which shouldn't be necessary anymore.

**Comment by bgyori** [comment]
These are confirmed to be okay on the latest hackathon branch (whose current state has also been merged into main).
