### ISSUE TITLE
scenario 1c contains  `k_1` and `k_2` parameters in the rate law that are not in the parameters section of the AMR

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#201]
Equation (10) of

> Tay, B. K., Roby, C. A., Wu, J. W., & Tan, D. Y. (2021). Dynamical analysis of universal masking on the pandemic. International Journal of Environmental Research and Public Health, 18(17). https://doi.org/10.3390/ijerph18179027

contains parameters $k_1$ and $k_2$ in the rate law, and they are in the rate law of transition `t_1`, 

https://github.com/indralab/mira/blob/56bf4c0d77919142684c8cbfb3521b7bf4470888/notebooks/hackathon_2023.07/scenario1_c.json#L129

But similar to #200 they are not in the parameters section of the AMR:

https://github.com/indralab/mira/blob/56bf4c0d77919142684c8cbfb3521b7bf4470888/notebooks/hackathon_2023.07/scenario1_c.json#L175-L224

**Comment by bgyori** [comment]
See my response to #200, this is just an issue with the particular commit your model import is temporarily pinned to.
