### ISSUE TITLE
Scenario 1c model missing a '1/N' term in the rate law expression

### ISSUE THREAD

**Issue by VigneshSella** [indralab/mira#203]
In [Scenario1c model](https://github.com/indralab/mira/blob/hackathon/notebooks/hackathon_2023.07/scenario1_c.json) at line [139](https://github.com/indralab/mira/blob/3748397324e7aa0cffea1c3ae3f53ae21d37a617/notebooks/hackathon_2023.07/scenario1_c.json#L139) there is no '1/N' term, I believe this yields incorrect units in the expression and such leads to failed calculations in subsequent calculations.

**Comment by VigneshSella** [comment]
The '1/N' term is present in Scenario 1a model

**Comment by djinnome** [comment]
confirmed this issue remains in the latest hackathon branch.

**Comment by bgyori** [comment]
This is fixed on the hackathon branch.
