### ISSUE TITLE
Scenario 2a (beat_var and beta_scale) are missing initial conditions array

### ISSUE THREAD

**Issue by VigneshSella** [indralab/mira#204]
For [scenario2a](https://github.com/indralab/mira/blob/hackathon/notebooks/hackathon_2023.07/scenario2_a_beta_scale_static.json), at this [line](https://github.com/indralab/mira/blob/3748397324e7aa0cffea1c3ae3f53ae21d37a617/notebooks/hackathon_2023.07/scenario2_a_beta_scale_static.json#L1353) there should be initial conditions for S,V,A,I,R. I believe the parameter values are:
S = 1
V = [V1, V2] = [0,0]
A = 0
I = 1e-6
R = 0.

This is from the MATLAB data provided by the paper author at their [GitHub](https://github.com/MehrshadSD/SARS-CoV-2-variants-of-concern-in-Ontario).

**Comment by VigneshSella** [comment]
Looks like the following are undefined initial conditions that should be included in the AMR:
{'S': 1, 'V1': 0.0, 'V2': 0.0, 'A': 0.0, 'I': 1e-6, 'R': 0.0, 'AR': 0.0, 'IR': 0.0, 'IV': 0.0, 'R2': 0.0, 'SVR': 0.0}

Note: Values are not necessarily correct, but I set them to the best of my understanding of the paper and ASKEM scenario handout.

**Comment by bgyori** [comment]
This is fixed on the hackathon branch. The initials were implemented in my notebook, they just weren't correctly included in the output.
