### ISSUE TITLE
Scenario 2a Incorrect values for parameters

### ISSUE THREAD

**Issue by VigneshSella** [indralab/mira#205]
**Beta, beta_v1, beta_v2, beta_R** are on the order of 1e-10. Whereas, in the [MATLAB data ](https://github.com/MehrshadSD/SARS-CoV-2-variants-of-concern-in-Ontario/blob/main/output.mat)provided by the paper author they are on the order of 1e-3. These values lead into a simulation which drops the # of infected to 0 after starting at 1e-6 (presumably because transmission rates are so low). 

This applies to the following .json AMRs:

1. https://github.com/indralab/mira/blob/hackathon/notebooks/hackathon_2023.07/scenario2_a_beta_scale_static.json
2. https://github.com/indralab/mira/blob/hackathon/notebooks/hackathon_2023.07/scenario2_a_beta_scale_var.json

**Comment by bgyori** [comment]
Interesting - according to the paper's supplementary materials, my numbers look correct, e.g.

![image](https://github.com/indralab/mira/assets/5939016/82ebe7f0-e8f2-4087-91d4-a9da105c9d4e)

Not sure where the difference comes from.

**Comment by VigneshSella** [comment]
Not sure either. But to my un-trained eyes these variables names seem slightly different than the ones in the AMR and MATLAB output.mat file. The MATLAB output.mat file has the variables titled as they are in the model, and with the difference in order of magnitude, transmission should be possible as opposed to when the beta variables are as defined (on the order of 1e-9/-10) then the simulation makes # of infected 0 after a few days.

**Comment by bgyori** [comment]
This is resolved on the latest hackathon branch. The issue was that the original model didn't directly use these parameters, they were multiplied by the absolute population first:

https://github.com/MehrshadSD/SARS-CoV-2-variants-of-concern-in-Ontario/blob/main/voc2_driver.m#L7-L12
