### ISSUE TITLE
When reading amr for Scenario 3, mira doesn't parse ControlledProduction

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#222]
Hi folks,

When reading in the [amr](https://raw.githubusercontent.com/indralab/mira/main/notebooks/evaluation_2023.07/eval_scenario3_base.json) for [scenario 3](https://github.com/indralab/mira/blob/main/notebooks/evaluation_2023.07/scenario3.ipynb), we get state variables for `S`, `I`, and `E`, but not for `V`.

I suspect that the problem is that `ControlledProduction` is generated

https://github.com/indralab/mira/blob/ae6469d4c48beeccba65c52a00e77528cd321288/mira/metamodel/templates.py#L11

 but not parsed.

https://github.com/indralab/mira/blob/ae6469d4c48beeccba65c52a00e77528cd321288/mira/sources/askenet/petrinet.py#L270-L308

**Comment by bgyori** [comment]
Indeed, that looks like a missing piece. We will fix this ASAP.

**Comment by bgyori** [comment]
Fixed in #223
