### ISSUE TITLE
scenario 3 template does not capture Viral load

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#230]
Here is how to reproduce the problem:

```python
>>> from mira.sources.askenet.petrinet import model_from_url
>>> SEIV_model_url = "https://raw.githubusercontent.com/indralab/mira/hackathon2/notebooks/evaluation_2023.07/eval_scenario3_base.json"
>>> template_model = model_from_url(SEIV_model_url)
>>> [t.name for t in template_model.templates]
['t1', 't2', 't3']
```
The problem appears to be that in the template model, `t4` was never parsed:

https://github.com/indralab/mira/blob/139d0039ed84273c828ca484cc538e49e000e275/notebooks/evaluation_2023.07/eval_scenario3_base.json#L104-L116

**Comment by djinnome** [comment]
Is this related to https://github.com/indralab/mira/issues/222 ?

**Comment by bgyori** [comment]
Is it possible that this was fixed already during the hackathon? Are you on
the latest MIRA main branch? If that isn't sufficient to solve it, I will
look into it!

**Comment by bgyori** [comment]
This definitely works on `main` so should work after and update.

**Comment by djinnome** [comment]
I can confirm that this works on `main` for me, too.
