### ISSUE TITLE
Add askemo term for vaccination rate

### ISSUE THREAD

**Issue by djinnome** [indralab/mira#85]
Hi folks,

the `nu` parameter in an SVIIvR model is the vaccination rate parameter.  Could we get an `askemo` term for vaccination rate?

**Comment by bgyori** [comment]
Hi @djinnome, I'm working on adding this. Can you point me to any documentation / publication where this term is used in context?

**Comment by djinnome** [comment]
It is the parameter associated with the `:vax` transition connecting the susceptible population (`S`) to the vaccinated susceptible population (`V`) in Figure 2(b) and 2(c) of the [Algebraic Framework for Structured Epidemiology paper](https://royalsocietypublishing.org/doi/10.1098/rsta.2021.0309)  Also, it is contained in the [SVIIvR model](https://github.com/AlgebraicJulia/ASKEM-demos/blob/master/data/SVIIvR.json) described in cell [6] of the [composition notebook](https://nbviewer.org/github/AlgebraicJulia/Structured-Epidemic-Modeling/blob/main/composition.ipynb)

**Comment by djinnome** [comment]
Lastly, it is the parameter that is being minimized subject to the constraint of no more than 10 cases per 100k in scenario 2 of the December demo.
